export const team = [ // core members details
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/arghamallick.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#FF9595",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/johndoe.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#A1FF90",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/johndoe.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#FF9595",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/johndoe.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#A1FF90",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/johndoe.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#A1FF90",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
    {
        "id": 0,
        "name": "John Doe",
        "image": "/assets/team/johndoe.png",
        "position": "Core, Event Management Team",
        "bgcolor": "#A1FF90",
        "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
    },
];

export const facultyCoordinators = {
    techhunt: [
        {
            "id": 0,
            "name": "John Doe",
            "image": "/assets/team/johndoe.png",
            "position": "Core, Event Management Team",
            "bgcolor": "#A1FF90",
            "linkedin": "/",
        },
    ],
    omegatrix: [],
    codebee: [],
    hackstorm: [],
    technomania: [],
    rocombat: [],
    ronavigator: [],
    rosoccer: [],
    roterrance: [],
    aquarace: [],
    efootball: [],
    fifa: [],
    khet: [],
    passionwithreels: [],
    shutterfusion: [],
    codebeejr: [],
    technomaniajr: [],
    hackstormjr: [],
};

export const studentCoordinators = {
    techhunt: [],
    omegatrix: [],
    codebee: [],
    hackstorm: [],
    technomania: [],
    rocombat: [],
    ronavigator: [],
    rosoccer: [],
    roterrance: [],
    aquarace: [],
    efootball: [],
    fifa: [],
    khet: [],
    passionwithreels: [],
    shutterfusion: [],
    codebeejr: [],
    technomaniajr: [],
    hackstormjr: [],
};

export const volunteers = {
    techhunt: [],
    omegatrix: [],
    codebee: [],
    hackstorm: [],
    technomania: [],
    rocombat: [],
    ronavigator: [],
    rosoccer: [],
    roterrance: [],
    aquarace: [],
    efootball: [],
    fifa: [],
    khet: [],
    passionwithreels: [],
    shutterfusion: [],
    codebeejr: [],
    technomaniajr: [],
    hackstormjr: [],
};