export const allTeams = [
    {
        teamName: "Core Team",
        members: [
            {
                "id": 6,
                "name": "DIBENDU PAUL",
                "department": "ECE",
                "roll": 11500322016,
                "year": "3rd year",
                "position": "Core",
                "team": "Event Management Team",
                "phone": 6290557916,
                "email": "dibendupaul49@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fdibendu_paul.jpg?alt=media&token=b0dd7eaf-6608-4ef9-958f-93fd5e2bdd3a",
                "image": "/assets/team/core/dibendu_paul.png",
                "linkedin": "https://www.linkedin.com/in/dibendu-paul-b05b80253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
                "bgcolor": "#FF9601"
            },
            {
                "id": 20,
                "name": "Srijita Mallick",
                "department": "IT",
                "roll": 11500222031,
                "year": "3rd year",
                "position": "Core",
                "team": "Event Management Team",
                "phone": 8017248950,
                "email": "srijita.it222031@bppimt.ac.in",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsrijita_mallick.png?alt=media&token=b22bee2a-57d4-4944-840d-11a7d110a1c6",
                "image": "/assets/team/core/srijita_mallick.png",
                "linkedin": "https://www.linkedin.com/in/srijita-mallick-10391a250/",
                "bgcolor": "#FF9615"
            },
            {
                "id": 23,
                "name": "Suryanshu Paul",
                "department": "CSE",
                "roll": 11500122005,
                "year": "3rd year",
                "position": "Core",
                "team": "Finance Management Team",
                "phone": 9433819721,
                "email": "suryanshupaul1990@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsuryanshu_paul.jpg?alt=media&token=d433a370-c63d-44da-b71c-130711317cea",
                "image": "/assets/team/core/suryanshu_paul.png",
                "linkedin": "https://www.linkedin.com/in/suryanshu-paul-2aa003253/",
                "bgcolor": "#FF9618"
            },
            {
                "id": 25,
                "name": "Tiasa Mahanty",
                "department": "ECE",
                "roll": 11500322044,
                "year": "3rd year",
                "position": "Core",
                "team": "Finance Management Team",
                "phone": 7980622205,
                "email": "tiasamahanty03@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Ftiasa_mahanty.jpg?alt=media&token=a3f7d5c6-03d0-43d4-b5b6-a4cf8b4107af",
                "image": "/assets/team/core/tiasa_mahanty.png",
                "linkedin": "https://www.linkedin.com/in/tiasa-mahanty-16647a267/",
                "bgcolor": "#FF9620"
            },
            {
                "id": 0,
                "name": "Akash Dey",
                "department": "BBA",
                "roll": 30105022005,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 7439698280,
                "email": "adey743969@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fakash_dey.jpg?alt=media&token=ccb455e0-7add-42e6-85e5-aca7d2b041df",
                "image": "/assets/team/core/akash_dey.png",
                "linkedin": "https://www.linkedin.com/in/akash-dey-b229a3279?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
                "bgcolor": "#FF9595"
            },
            {
                "id": 1,
                "name": "Aratrika Samanta",
                "department": "IT",
                "roll": 11500222061,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 7363844572,
                "email": "aratrikasamanta060203@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Faratrika_samanta.jpg?alt=media&token=31657705-34bb-4b04-9cc3-f27f9a85801d",
                "image": "/assets/team/core/aratrika_samanta.png",
                "linkedin": "https://www.linkedin.com/in/aratrika-samanta-67a1b5268/",
                "bgcolor": "#FF9596"
            },
            {
                "id": 5,
                "name": "Debosmita Paul",
                "department": "ECE",
                "roll": 11500322020,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 7003637202,
                "email": "debosmita221@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fdebosmita_paul.jpg?alt=media&token=e0fcf644-2f08-452d-94c0-a18c5a750ee4",
                "image": "/assets/team/core/debosmita_paul.png",
                "linkedin": "https://www.linkedin.com/in/debosmita-paul-4a6741267/",
                "bgcolor": "#FF9600"
            },
            {
                "id": 7,
                "name": "Gourab Dey",
                "department": "MCA",
                "roll": 11571024039,
                "year": "1st year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 6291008213,
                "email": "gourabdey1357@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fgourab_dey.jpg?alt=media&token=3ac1e46b-beba-462d-96d7-19ff6325af5e",
                "image": "/assets/team/core/gourab_dey.png",
                "linkedin": "https://www.linkedin.com/in/gourab-dey?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
                "bgcolor": "#FF9602"
            },
            {
                "id": 9,
                "name": "Navoneel Dey",
                "department": "CSE",
                "roll": 11500122047,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 9153713912,
                "email": "navoneeldey3@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fnavoneel_dey.jpg?alt=media&token=384b7731-c0c6-4160-999b-84ee7887c6f9",
                "image": "/assets/team/core/navoneel_dey.png",
                "linkedin": "https://www.linkedin.com/in/navoneel-dey-a7350a259/",
                "bgcolor": "#FF9604"
            },
            {
                "id": 10,
                "name": "Payel Pal",
                "department": "CSE",
                "roll": 11500122028,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 8617743569,
                "email": "payelofficial.2020@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fpayel_pal.jpg?alt=media&token=fa934d17-4e90-4071-a2b1-1223fefba61c",
                "image": "/assets/team/core/payel_pal.png",
                "linkedin": "https://www.linkedin.com/in/payel-pal-596856248/",
                "bgcolor": "#FF9605"
            },
            {
                "id": 14,
                "name": "Sanjib Sen",
                "department": "IT",
                "roll": 11500222070,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 8777481260,
                "email": "sanjibsen234@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsanjib_sen.JPG?alt=media&token=a5c3bccf-16b8-4012-a142-fdb8090695da",
                "image": "/assets/team/core/sanjib_sen.png",
                "linkedin": "https://www.linkedin.com/in/sanjibsen234/",
                "bgcolor": "#FF9609"
            },
            {
                "id": 17,
                "name": "Somnath Chakraborty",
                "department": "ECE",
                "roll": 11500322072,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 8902211316,
                "email": "somnathchak315@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsomnath_chakraborty.png?alt=media&token=87bb4823-9f17-42d6-bfcb-de0af25c3542",
                "image": "/assets/team/core/somnath_chakraborty.png",
                "linkedin": "https://www.linkedin.com/in/somnath-chakraborty-5b4434253/",
                "bgcolor": "#FF9612"
            },
            {
                "id": 18,
                "name": "Sougata Roy Chowdhury",
                "department": "EE",
                "roll": 11501622010,
                "year": "3rd year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 8512969534,
                "email": "sougataroychowdhury04@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsougata_roy_chowdhury.jpg?alt=media&token=23fa7d33-d69d-46c0-be19-f2ad8efe5666",
                "image": "/assets/team/core/sougata_roy_chowdhury.png",
                "linkedin": "https://www.linkedin.com/in/sougata-roy-chowdhury-a459b3267/",
                "bgcolor": "#FF9613"
            },
            {
                "id": 22,
                "name": "Sukumar Poddar",
                "department": "MCA",
                "roll": 11571024015,
                "year": "1st year",
                "position": "Core",
                "team": "Publicity & Sponsorship Management Team",
                "phone": 6206297928,
                "email": "sukumarpoddar.mca2641@bppimt.ac.in",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsukumar_poddar.jpg?alt=media&token=83854b4b-9c91-479b-85fc-e880eae11932",
                "image": "/assets/team/core/sukumar_poddar.png",
                "linkedin": "https://www.linkedin.com/in/sukumarpoddar/",
                "bgcolor": "#FF9617"
            },
            {
                "id": 4,
                "name": "Chandrasish Bhattacharya",
                "department": "CSE",
                "roll": 11500122077,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 7439476561,
                "email": "chandrasish3456@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fchandrasish_bhattacharya.jpeg?alt=media&token=c39d71b4-0912-4c87-8e83-c9d854fb95c9",
                "image": "/assets/team/core/chandrasish_bhattacharya.png",
                "linkedin": "https://www.linkedin.com/in/chandrasish-bhattacharya/",
                "bgcolor": "#FF9599"
            },
            {
                "id": 8,
                "name": "Indrani Banik",
                "department": "MCA",
                "roll": 11571024040,
                "year": "1st year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 7439815597,
                "email": "indranibanik2002@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Findrani_banik.png?alt=media&token=9d1bb801-913d-44ab-8e2f-2dec79ca2cdd",
                "image": "/assets/team/core/indrani_banik.png",
                "linkedin": "https://www.linkedin.com/in/indrani-banik-a8684a264/",
                "bgcolor": "#FF9603"
            },
            {
                "id": 11,
                "name": "Rohit Yadav",
                "department": "EE",
                "roll": 11501622009,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 7980172948,
                "email": "rohityadavji1922@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Frohit_yadav.jpg?alt=media&token=cc88bb96-cb92-44ff-857f-76dca5c8ad31",
                "image": "/assets/team/core/rohit_yadav.png",
                "linkedin": "https://www.linkedin.com",
                "bgcolor": "#FF9606"
            },
            {
                "id": 12,
                "name": "Rupsa Guha Roy",
                "department": "BCA",
                "roll": 30101222077,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 9007632382,
                "email": "guharoyrupsa02@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Frupsa_guha_roy.jpg?alt=media&token=d59f8e62-e617-45dc-be7c-38f9f68dcf2b",
                "image": "/assets/team/core/rupsa_guha_roy.png",
                "linkedin": "https://www.linkedin.com/in/rupsa-guha-roy-022172281?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
                "bgcolor": "#FF9607"
            },
            {
                "id": 13,
                "name": "Sampriti Ghosh",
                "department": "ECE",
                "roll": 11500322067,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 7407129866,
                "email": "sampriti.ece322067@bppimt.ac.in",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsampriti_ghosh.jpg?alt=media&token=7c346ba1-ea73-4a69-b0a5-9e892760690c",
                "image": "/assets/team/core/sampriti_ghosh.png",
                "linkedin": "https://www.linkedin.com/in/sampriti-ghosh-7629b6267/",
                "bgcolor": "#FF9608"
            },
            {
                "id": 15,
                "name": "Shirodhrit Bhowmick",
                "department": "IT",
                "roll": 11500222013,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 8420465695,
                "email": "Shirodhritbhowmick15@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fshirodhrit_bhowmick.JPG?alt=media&token=c384a857-b536-4cfc-bb8c-63f1ae2824c3",
                "image": "/assets/team/core/shirodhrit_bhowmick.png",
                "linkedin": "https://www.linkedin.com/in/shirodhrit-bhowmick-39824525b/",
                "bgcolor": "#FF9610"
            },
            {
                "id": 16,
                "name": "Shreya Bhattacharya",
                "department": "ECE",
                "roll": 11500322080,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 8240540834,
                "email": "shreya.ece322080@bppimt.ac.in",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fshreya_bhattacharya.jpg?alt=media&token=076c1c45-3a60-43fc-a4c0-15ab20eeefa8",
                "image": "/assets/team/core/shreya_bhattacharya.png",
                "linkedin": "https://www.linkedin.com/in/shreya-bhattacharya-b17071246/",
                "bgcolor": "#FF9611"
            },
            {
                "id": 19,
                "name": "Srijit Pal",
                "department": "IT",
                "roll": 11500222077,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 9073800392,
                "email": "srijit.activities@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsrijit_pal.jpeg?alt=media&token=7561978c-cb36-41fd-b460-3ae492c51ddd",
                "image": "/assets/team/core/srijit_pal.png",
                "linkedin": "https://www.linkedin.com/in/srijit-pal-4995b1267/",
                "bgcolor": "#FF9614"
            },
            {
                "id": 21,
                "name": "Srutikana Das",
                "department": "CSE",
                "roll": 11500122122,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 9123033239,
                "email": "srutikanad@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fsrutikana_das.jpg?alt=media&token=579c933a-2775-4dc8-8c65-1fa6bfa76f9f",
                "image": "/assets/team/core/srutikana_das.png",
                "linkedin": "https://www.linkedin.com/in/srutikana-das-aa4809253/",
                "bgcolor": "#FF9616"
            },
            {
                "id": 24,
                "name": "Tanushka Joshi",
                "department": "EE",
                "roll": 11501622002,
                "year": "3rd year",
                "position": "Core",
                "team": "Discipline & Hospitality Management Team",
                "phone": 9874083342,
                "email": "tanushkajoshi08@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Ftanushka_joshi.jpg?alt=media&token=836a4adb-1b78-41db-883c-6793f5696267",
                "image": "/assets/team/core/tanushka_joshi.png",
                "linkedin": "https://www.linkedin.com/in/tanushka-joshi-3263062b8/",
                "bgcolor": "#FF9619"
            },
            {
                "id": 2,
                "name": "Archak Nath",
                "department": "IT",
                "roll": 11500222053,
                "year": "3rd year",
                "position": "Core",
                "team": "Creative Management Team",
                "phone": 9330397140,
                "email": "archak.nath02052004@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Farchak_nath.png?alt=media&token=1d4d63f8-2309-4d3a-80db-16fbdd86fb64",
                "image": "/assets/team/core/archak_nath.png",
                "linkedin": "https://www.linkedin.com/in/archak-nath-a682aa247/",
                "bgcolor": "#FF9597"
            },
            {
                "id": 3,
                "name": "Argha Mallick",
                "department": "CSE",
                "roll": 11500122014,
                "year": "3rd year",
                "position": "Core",
                "team": "Creative Management Team",
                "phone": 9330927535,
                "email": "arghamallick608@gmail.com",
                "bg_image": "https://firebasestorage.googleapis.com/v0/b/artco-bb7b5.appspot.com/o/core_members%2Fargha_mallick.jpg?alt=media&token=ec24d6c4-86b6-468f-b725-839ec9a2d58c",
                "image": "/assets/team/core/argha_mallick.png",
                "linkedin": "https://www.linkedin.com/in/iamarghamallick/",
                "bgcolor": "#FF9598"
            }
        ],
    },
    {
        teamName: "Tech Hunt",
        members: {
            faculty: [
                {
                    name: "Faculty Name1",
                    position: "faculty",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "Faculty Name2",
                    position: "faculty",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],

            student: [
                {
                    name: "student Name1",
                    position: "student",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "student Name2",
                    position: "student",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],

            volunteer: [
                {
                    name: "volunteer Name1",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name2",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name3",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name3",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],
        },
    },
    {
        teamName: "Omegatrix",
        members: {
            faculty: [
                {
                    name: "Faculty Name1",
                    position: "faculty",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "Faculty Name2",
                    position: "faculty",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],

            student: [
                {
                    name: "student Name1",
                    position: "student",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "student Name2",
                    position: "student",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],

            volunteer: [
                {
                    name: "volunteer Name1",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name2",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name3",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
                {
                    name: "volunteer Name4",
                    position: "volunteer",
                    department: "CSE",
                    phone: "1234567890",
                },
            ],
        },
    },
];
